# Model arguments
model_name_or_path: /opt/ml/input/data/model
torch_dtype: auto
use_flash_attention_2: true

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

load_in_4bit: true

# Data training arguments
dataset_mixer:
  /opt/ml/input/data/train: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: zephyr-7b-sft-lora
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
optim: "adamw_bnb_8bit"
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: /opt/ml/model
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
logging_dir: "/opt/ml/output/tensorboard"
report_to:
- tensorboard
save_strategy: "no"
save_total_limit: null
seed: 42